### ISSUE TITLE
some readme ... 

### ISSUE THREAD

**Issue by sunnysideup** [BiffBangPow/silverstripe-fixtureloader#1]
Hi,

Looks interesting. Is this for testing or for populating a new site.  Some readme would be super helpful.

**Comment by TimBBP** [comment]
Hi.    Yes, this is a tool for populating sites with test data.  It's currently an internal tool and it contains some hard-coded assumptions, so a readme for other people to use is likely to cause a lot of headaches at this time.    We do have plans to develop it further, at which point we'll produce some proper documentation!
